//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSLinkChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YSLinkChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgula.
        /// </summary>
        public static string btnCheck {
            get {
                return ResourceManager.GetString("btnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV olarak aktar.
        /// </summary>
        public static string btnCSV {
            get {
                return ResourceManager.GetString("btnCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dış bağlantılar.
        /// </summary>
        public static string btnExternal {
            get {
                return ResourceManager.GetString("btnExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç bağlantılar.
        /// </summary>
        public static string btnInternal {
            get {
                return ResourceManager.GetString("btnInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF olarak aktar.
        /// </summary>
        public static string btnPDF {
            get {
                return ResourceManager.GetString("btnPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm bağlantılar.
        /// </summary>
        public static string btnTotal {
            get {
                return ResourceManager.GetString("btnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT olarak aktar.
        /// </summary>
        public static string btnTXT {
            get {
                return ResourceManager.GetString("btnTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metin.
        /// </summary>
        public static string dgText {
            get {
                return ResourceManager.GetString("dgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string dgURL {
            get {
                return ResourceManager.GetString("dgURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string lblAdress {
            get {
                return ResourceManager.GetString("lblAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres bağlantı içermiyor..
        /// </summary>
        public static string msg_address {
            get {
                return ResourceManager.GetString("msg_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV dışa aktarıldı..
        /// </summary>
        public static string msg_csv {
            get {
                return ResourceManager.GetString("msg_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantılar listelendi..
        /// </summary>
        public static string msg_listed {
            get {
                return ResourceManager.GetString("msg_listed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YSLinkChecker yüklendi..
        /// </summary>
        public static string msg_load {
            get {
                return ResourceManager.GetString("msg_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF dışa aktarıldı..
        /// </summary>
        public static string msg_pdf {
            get {
                return ResourceManager.GetString("msg_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT dışa edildi..
        /// </summary>
        public static string msg_txt {
            get {
                return ResourceManager.GetString("msg_txt", resourceCulture);
            }
        }
    }
}
